# 此工作流程使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受
# 单独的服务条款、隐私政策和支持
# 文档的约束。
 
 # 此工作流程签出代码，执行 Codacy 安全扫描
# 并将结果与
# GitHub 高级安全代码扫描功能集成。有关
# Codacy 安全扫描操作用法和参数的更多信息，请参阅
# `https://github.com/codacy/codacy-analysis-cli-action.`
# 有关 Codacy Analysis CLI 的更多信息，请参阅
# `https://github.com/codacy/codacy-analysis-cli.`
 
 name: Codacy Security Scan 
 
 on: 
   push: 
     branches: [ "master" ] 
   pull_request: 
     # 以下分支必须是以上分支的子集
     branches: [ "master" ] 
   schedule: 
     - cron: '38 8 * * 5' 
 
 permissions: 
   contents: read 
 
 jobs: 
   codacy-security-scan: 
     permissions: 
       contents: read #供 actions/checkout 获取代码
       security-events: write #供 github/codeql-action/upload-sarif 上传 SARIF 结果
       actions: read # github/codeql-action/upload-sarif 仅私有仓库需要此项来获取 Action 运行状态
     name: Codacy Security Scan 
     runs-on: ubuntu-latest 
     steps: 
       # 将仓库签出到 GitHub Actions运行器
       - name: Checkout code 
         uses: actions/checkout@v4 
 
       # 执行 Codacy Analysis CLI 并生成 SARIF 输出，其中包含分析期间识别的安全问题
       - name: Run Codacy Analysis CLI 
         uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b 
         with: 
           # 访问 `https://github.com/codacy/codacy-analysis-cli#project-token` 从您的 Codacy 仓库获取项目令牌
           # 您也可以省略令牌并运行支持默认配置的工具
           project-token: ${{ secrets.CODACY_PROJECT_TOKEN }} 
           verbose: true 
           output: results.sarif 
           format: sarif 
           # 调整非安全问题的严重性
           gh-code-scanning-compat: true 
           # 强制退出代码为 0 以允许生成 SARIF 文件
           # 这会将有关 PR 拒绝的控制权移交给 GitHub 端
           max-allowed-issues: 2147483647 
 
       # 导入 GPG 密钥
       - name: Import GPG key
         uses: crazy-max/ghaction-gpg@v2
         with:
           gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
           passphrase: ${{ secrets.PASSPHRASE }}

       # 使用 GPG 签名 SARIF 文件
       - name: Sign SARIF file
         run: gpg --batch --yes --armor --detach-sign -o codacy-results.sarif.asc codacy-results.sarif

       # 上传 SARIF 文件到 GitHub Code Scanning
       - name: Upload SARIF results file
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: codacy-results.sarif

       # 上传 GPG 签名文件到 Release
       - name: Upload GPG signature to Release
         if: startsWith(github.ref, 'refs/tags/')
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ github.event.release.upload_url }}
           asset_path: ./codacy-results.sarif.asc
           asset_name: codacy-results.sarif.asc
           asset_content_type: application/pgp-signature