name: Sync to Gitcode

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置SSH密钥（Gitcode）
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 接受 Codeup 主机密钥
        run: |
          echo -e "Host codeup.aliyun.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          ssh-keyscan codeup.aliyun.com >> ~/.ssh/known_hosts

      - name: 配置Git用户信息（Gitcode）
        run: |
          git config --global user.name "xiaomizhou"
          git config --global user.email "qixiaoxin@stu.sqxy.edu.cn"

      - name: 添加Codeup远程仓库
        run: |
          git remote add codeup git@codeup.aliyun.com:6837184580f513ec112a534b/astrbot_plugin_treasure_bag.git

      - name: 同步代码到Codeup
        run: |
          git push codeup master