# 此工作流程使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档的约束。
 
 # This workflow integrates Pyre with GitHub's 
 # Code Scanning feature. 
 # 
 # Pyre is a performant type checker for Python compliant with 
 # PEP 484. Pyre can analyze codebases with millions of lines 
 # of code incrementally – providing instantaneous feedback 
 # to developers as they write code. 
 # 
 # See `https://pyre-check.org` 
 
 name: Pyre 
 
 on: 
   workflow_dispatch: 
   push: 
     branches: [ "master" ] 
   pull_request: 
     branches: [ "master" ] 
 
 permissions: 
     contents: read 
 
 jobs: 
   pyre: 
     name: Pyre on ${{ matrix.os }} with Python ${{ matrix.python-version }}
     permissions: 
       actions: read 
       contents: read 
       security-events: write 
     strategy: 
       matrix: 
         os: [ubuntu-latest, windows-latest, macos-latest] 
         python-version: [3.8, 3.9, 3.11, 3.13] 
     runs-on: ${{ matrix.os }} 
     steps: 
       - uses: actions/checkout@v4 
         with: 
           submodules: true 
 
       - name: Set up Python ${{ matrix.python-version }} 
         uses: actions/setup-python@v5 
         with: 
           python-version: ${{ matrix.python-version }} 
 
       - name: Run Pyre 
         uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d 
         with: 
           # 要自定义这些输入：
           # 参见 `https://github.com/facebook/pyre-action#inputs`
           repo-directory: './' 
           requirements-path: 'requirements.txt'