# 此工作流使用了未经 GitHub 认证的操作。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档的约束。 
 
 # 此工作流将 Python 静态分析器 (Pysa) 与 GitHub 的代码扫描功能集成。
#
# Python 静态分析器 (Pysa) 是一个专注于安全的静态分析工具，它跟踪数据从源头到危险位置的流向。
#
# 详情请参阅 `https://pyre-check.org/docs/pysa-basics/` 
 
 name: Pysa 
 
 on: 
   workflow_dispatch: 
   push: 
     branches: [ "main" ] 
   pull_request: 
     branches: [ "main" ] 
   schedule: 
     - cron: '24 4 * * 1' 
 
 permissions: 
     contents: read 
 
 jobs: 
   pysa:
     name: Pysa on ${{ matrix.os }} with Python ${{ matrix.python-version }} 
     permissions:
       actions: read
       contents: read
       security-events: write

     strategy:
       matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.11, 3.13]

     runs-on: ${{ matrix.os }} 
     steps: 
       - uses: actions/checkout@v4 
         with: 
           submodules: true 
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}

       - name: Run Pysa 
         uses: facebook/pysa-action@f46a63777e59268613bd6e2ff4e29f144ca9e88b 
         with: 
           # 要自定义这些输入：
           # 请参阅 `https://github.com/facebook/pysa-action#inputs` 
           repo-directory: './' 
           requirements-path: 'requirements.txt' 
           infer-types: true 
           include-default-sapp-filters: true