name: Roast My PR

on:
  pull_request:
    # Run this action whenever a pull request is created or updated
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Roast My PR
      uses: ./
      with:
        github-token: ${{ secrets.TOKEN }}
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}