name: Sync Source to Cloud Native Build

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to Cloud Native Build
        run: |
          git remote add cnb https://cnb.cool/XMZZUZHI/astrbot_plugin_treasure_bag.git
          git config --local user.name cnb.ZsPOlmV7wGA
          git config --local user.email "zk7kcFWo1BLRrYWf4o4zKF+cnb.ZsPOlmV7wGA@noreply.cnb.cool"
          git push cnb master